### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by RyanPWalker** [jchook/uuid-random#13]
```
import uuid from 'uuid-random';
uuid();
```
Generates `c7ffe9d4-60bb-4a1d-bf8c-994749883c72` every. single.  time.  On any browser or device.  Same webpage.

Node 12.14.1
npm 6.13.4
React 16.10.2
Babel 7.0.0
Webpack 3.8.1

**Comment by jchook** [comment]
@RyanPWalker thanks for the report. So far I cannot reproduce. Is it possible your uuid got memoized farther up the call stack?

Have you tried reproducing the issue in an isolated/clean environment?

**Comment by RyanPWalker** [comment]
Now that you mention it, it could be on the server that's rendering the page.  I'll check it out.

**Comment by jchook** [comment]
Yeah web server cache seems like a likely culprit.

**Comment by RyanPWalker** [comment]
Yep you were right, sorry for the false alarm.
