### ISSUE TITLE
Conversion methods

### ISSUE THREAD

**Issue by Hamper** [jchook/uuid-random#19]
Can you add simple conversion methods for uuid.toString() and uuid.toBin() to module? Because sometimes both formats needed with same value.

**Comment by jchook** [comment]
Yea that seems like a reasonable request. We already have that function, just need to expose it.

**Comment by jchook** [comment]
If you want something in the meantime, you have some [options](https://www.npmjs.com/search?q=uuid%20parse).

**Comment by jchook** [comment]
Since other libraries already solve this problem, I will close this issue.
